name: periodic
description: A periodic widget (and dialog) to choose a recurring pattern.
version: 1.0.0+1
homepage: https://github.com/tolumania/periodic
repository: https://github.com/tolumania/periodic

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 
  customtogglebuttons: 
  flutter_hooks: ^0.18.0
  freezed_annotation: 
  group_radio_button: 
  hooks_riverpod: ^0.14.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  effective_dart: 
  freezed: 

flutter: